

const palavrasSorteio =
    [
        "arcar", "artes", "atriz", "atras", "bolas", "basta", "briga", "beijo", "bicar", "corte",
        "casar", "carro", "casca", "cerca", "caldo", "dedar", "dores", "raios", "doida", "falar",
        "festa", "fazer", "facil", "fugir", "gente", "gosto", "garra", "girar", "gordo", "habil",
        "haver", "hifen", "heroi", "haste", "harpa", "iscas", "indio", "irmao", "ideal", "jeito",
        "jogar", "jaspe", "jarra", "junto", "kombi", "kendo", "karma", "kilos", "kites", "louro",
        "lavar", "linda", "lacre", "lista", "morte", "masca", "mente", "minto", "mosca", "navio",
        "nozes", "nuvem", "ninho", "noite", "ostra", "outro", "ovulo", "ontem", "orgao", "parar",
        "pasto", "poste", "pomba", "quase", "quero", "quilo", "queda", "quota", "ratos", "rosto",
        "resto", "rival", "rodar", "sorte", "susto", "sabor", "sacar", "tarde", "tocar", "tigre",
        "torta", "tenso", "unico", "urrar", "untar", "vacas", "viver", "vazio", "vagar", "venda",
        "xucro", "xampu", "xenon", "xerox", "xingo", "ziper", "zumba", "zinco", "zelar", "zebra",
        "abrir", "achar", "acaso", "adiar", "afiar", "andar", "apelo", "apoio", "apuro", "ardor",
        "areia", "assar", "astro", "atual", "aviao", "baile", "balde", "banho", "barco", "beber",
        "berro", "bingo", "blusa", "bordo", "brasa", "bravo", "breve", "brisa", "broto", "cacho",
        "caixa", "calor", "canto", "capaz", "carga", "ceder", "censo", "cerco", "ciclo", "cinco",
        "clima", "colar", "coral", "couro", "criar", "crime", "crise", "curar", "curso", "danar",
        "dever", "dizer", "doido", "drama", "durar", "ecoar", "etapa", "exame", "falha", "fardo",
        "ferro", "filme", "final", "firma", "fluxo", "forca", "forma", "fraco", "fruta", "fundo",
        "furor"
    ];


// aqui ficam as palavras que o usuário pode chutar (agora incluindo TODAS as de sorteio)

const palavrasChute =
    [
        "arcar", "artes", "atriz", "atras", "bolas", "basta", "briga", "beijo", "bicar", "corte",
        "casar", "carro", "casca", "cerca", "caldo", "dedar", "dores", "raios", "doida", "falar",
        "festa", "fazer", "facil", "fugir", "gente", "gosto", "garra", "girar", "gordo", "habil",
        "haver", "hifen", "heroi", "haste", "harpa", "iscas", "indio", "irmao", "ideal", "jeito",
        "jogar", "jaspe", "jarra", "junto", "kombi", "kendo", "karma", "kilos", "kites", "louro",
        "lavar", "linda", "lacre", "lista", "morte", "masca", "mente", "minto", "mosca", "navio",
        "nozes", "nuvem", "ninho", "noite", "ostra", "outro", "ovulo", "ontem", "orgao", "parar",
        "pasto", "poste", "pomba", "quase", "quero", "quilo", "queda", "quota", "ratos", "rosto",
        "resto", "rival", "rodar", "sorte", "susto", "sabor", "sacar", "tarde", "tocar", "tigre",
        "torta", "tenso", "unico", "urrar", "untar", "vacas", "viver", "vazio", "vagar", "venda",
        "xucro", "xampu", "xenon", "xerox", "xingo", "ziper", "zumba", "zinco", "zelar", "zebra",
        "abrir", "achar", "acaso", "adiar", "afiar", "andar", "apelo", "apoio", "apuro", "ardor",
        "areia", "assar", "astro", "atual", "aviao", "baile", "balde", "banho", "barco", "beber",
        "berro", "bingo", "blusa", "bordo", "brasa", "bravo", "breve", "brisa", "broto", "cacho",
        "caixa", "calor", "canto", "capaz", "carga", "ceder", "censo", "cerco", "ciclo", "cinco",
        "clima", "colar", "coral", "couro", "criar", "crime", "crise", "curar", "curso", "danar",
        "dever", "dizer", "doido", "drama", "durar", "ecoar", "etapa", "exame", "falha", "fardo",
        "ferro", "filme", "final", "firma", "fluxo", "forca", "forma", "fraco", "fruta", "fundo",
        "furor",
        "afago", "agora", "alado", "amigo", "anexo", "banco", "barro", "bicho", "bocal", "bruto",
        "caber", "calma", "cesta", "campo", "claro", "dardo", "denso", "deter", "doces", "drops",
        "elite", "entes", "ereto", "exato", "facho", "gasto", "germe", "golpe", "gruta", "ganso",
        "haras", "harem", "hecta", "horta", "humor", "imune", "inata", "irado", "isola", "janta",
        "jarda", "judeu", "justo", "junta", "kayak", "lapis", "lutar", "lesao", "leigo", "lento",
        "magro", "malho", "manto", "mocho", "molho", "mural", "nariz", "ninar", "nobre", "obeso",
        "obrar", "otica", "oxida", "pardo", "pavor", "pilar", "pobre", "pular", "quipa", "raiar",
        "reler", "rigor", "rimel", "roseo", "sabia", "sadio", "salmo", "sapos", "sogra", "sogro",
        "tacho", "tempo", "tonto", "truco", "troca", "troco", "ulema", "umbral", "urano", "ursos", 
        "xibiu", "xingu", "zanga", "zumbi",
        "abade", "acude", "afeto", "agudo", "aluno", "amado", "ambar", "anzol", "aroma", "asilo",
        "atomo", "atrio", "aureo", "autor", "aveia", "aviso", "azeda", "bacia", "bafo", "balsa",
        "banal", "bando", "banzo", "batom", "bedel", "benca", "bilro", "birra", "bispo", "boato",
        "bobao", "boate", "bolar", "bonde", "bonus", "botao", "brace", "brejo", "bruma", "bufao",
        "bumba", "burao", "burro", "busao", "cabra", "cacau", "cacto", "cafun", "caico", "calmo",
        "campe", "canal", "canil", "capuz", "carne", "carva", "casso", "casta", "catre", "causa",
        "cavar", "cedro", "ceifa", "cerro", "cesar", "cessa", "cesto", "cetro", "chale", "chato",
        "chefe", "chibo", "choro", "chova", "chulo", "cidra", "cifra", "cinza", "circo", "cirio",
        "cisto", "clero", "clube", "coala", "cobre", "cocar", "cocho", "codal", "cogum", "coice",
        "colch", "colhe", "color", "comer", "comum", "conta", "corja", "coroa", "corpo", "corre",
        "corso", "coser", "costu", "craca", "crase", "crato", "cravo", "credo", "crepe", "creso",
        "crica", "croma", "cromo", "cruel", "crush", "cruze", "cuida", "cujas", "cujos", "culta",
        "cumbo", "cunha", "curai", "curio", "curta", "curto", "custa", "cutis", "dacao", "dador",
        "danca", "dando", "danta", "darga", "darma", "datar", "datil", "debut", "deixa", "deles",
        "demos", "dende", "dente", "depor", "derme", "desce", "desde", "despe", "dessa", "deste",
        "detem", "deusa", "devia", "devir", "diale", "diana", "dicar", "dieta", "digno", "dilei",
        "dilu", "dinde", "diodo", "dique", "disco", "dital", "ditar", "ditos", "divas", "dobra",
        "dobre", "dolar", "dolce", "domar", "donde", "dongo", "dorso", "dosar", "doses", "douto",
        "draga", "drena", "ducha", "dunas", "dupla", "duque", "ebano", "idade", "igual", "ileso",
        "impar", "index", "inves", "jabá", "jaca", "jaez", "joana", "joias", "jorge", "julho",
        "junho", "justa", "labia", "lacio", "lagoa", "laran", "largo", "larva", "lasca", "lastro",
        "laudo", "laura", "lebre", "legal", "legua", "leite", "leito", "lemes", "lenço", "lenta",
        "leque", "lerdo", "lesma", "leste", "letal", "letra", "levar", "lheis", "lhama", "lider",
        "ligar", "limbo", "limpo", "linha", "linho", "lirio", "lisos", "litor", "livro", "lizar",
        "lobby", "lobos", "local", "locar", "lodo", "logia", "logro", "loica", "loira", "lomba",
        "longe", "longo", "lopas", "lorde", "lote", "louca", "louco", "lousa", "lucro", "lugar",
        "lume", "lunar", "lupus", "luzes"
    ];

module.exports = { palavrasChute, palavrasSorteio };